version: '3'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443 # for ssl
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=ticket-booking
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080